### PR TITLE
Added necessary package

### PR DESCRIPTION
**Pull request by Szalacinski**

### CODE REVIEW

**Comment by Szalacinski** [comment]
Compilation also seems to fail on:

`/home/user/Documents/opentoonz/toonz/sources/common/tipc/tipc.cpp:465:90: error: invalid cast from type ‘QAtomicInt’ to type ‘int’
  return QString::number(QCoreApplication::applicationPid()) + "_" + QString::number((int)count);`

**Comment by Szalacinski** [comment]
That last casting problem is because I don't have the proper library.  I have QT 5.2.1, while the cast operator was introduced in 5.3.

**Comment by Szalacinski** [comment]
These changes may or may not depend on versions, so if they don't work on newer versions, then I'll need to upgrade.  I'm planning to once 16.04 is launched as stable.

**Comment by ideasman42** [comment]
Re: "Compilation Fails" - whats the error?

**Comment by Szalacinski** [comment]
@ideasman42 
`/home/user/Downloads/opentoonz/toonz/sources/common/tgl/tgl.cpp:714:7: error: token "@" is not valid in preprocessor expressions
 #elif @unknow platform !'

**Comment by andreygursky** [comment]
> #elif @unknow platform

@Szalacinski: Have you noticed my comment on this issue: https://github.com/opentoonz/opentoonz/pull/51#issuecomment-203150550?

If you hit this, it seems your platform is not WIN32/MACOSX/LINUX and thus really "unsupported". However if it is BSD, maybe you just have to catch it in CMake config and set LINUX.

**Comment by ideasman42** [comment]
Note that supporting other Unix's is fine, but would rather not do this when its complicating Linux portability patches.

Keep in mind in 100's of places in the existing code logic is split between Win32/OSX/Linux, so going over all of them and adding an extra case is not really within the scope of this patch.

**Comment by andreygursky** [comment]
@Szalacinski:
> That last casting problem is because I don't have the proper library. I have QT 5.2.1, while the cast operator was introduced in 5.3.

Qt 4.8.7 has it, but not Qt 5.2.1? Qt is famous of it's very good documentation, but I can't find which casts are available and since what version.

**Comment by xenogenesi** [comment]
About the preprocessor error, I would rather keep the error for the unknown platform like [here](https://github.com/xenogenesi/opentoonz/commit/1270ef0e07c90761401e6cded43358937d40d33e)

**Comment by Szalacinski** [comment]
@andreygursky @ideasman42 Actually, I'm running Linux Mint 17.3.  Regular Linux kernel and all.

**Comment by Szalacinski** [comment]
@andreygursky Casting was introduced in the QAtomicInteger parent class in 5.3:
https://doc.qt.io/qt-5/qatomicinteger.html#operator-T

**Comment by ideasman42** [comment]
Committed change to package. Other build issues should be handled separately.

**Pull request closed without merging**
