### PR TITLE
Linux fix wip

### PR DESCRIPTION
**Pull request by razvanc-r**
With the following modifications I managed to compile up to 100% on linux (Ubuntu 15.10).

**NOTE** the location of `Qt5`, which is installed manually. For this to work I had to follow the OSX build instructions:

- go to `thirdparty/tiff-4.0.3` and `./configure && make`
- go to `thirdparty/libpng-1.6.21` and `./configure && make`
- use `boost v1.55` as instructed
- install `Qt5` manually

I'm having linkage errors at the end of course.

*edit*: wanted to apply this to `linux_fix_wip`... probably skipped a step or something obvious (as this is my first pull request...)

### CODE REVIEW

**Comment by b4zz4** [comment]
¿You could publish the list of dependencies for GNU/linux?

**Comment by mmuman** [comment]
@b4zz4 someone mentionned https://gist.github.com/m-shibata/f08da942c9511fd3323d elsewhere.

**Comment by b4zz4** [comment]
Not compiler. I think that the problem is the sdk of quicktime

~~~
Please set them or make sure they are set and tested correctly in the
CMake files:
QT_LIB
~~~

François Revol:
> @b4zz4 someone mentionned https://gist.github.com/m-shibata/f08da942c9511fd3323d elsewhere.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ideasman42/opentoonz/pull/2#issuecomment-202556243
> 

-- 
http://maquinaslibres.tk
gpg: http://ba.zza.pl/bazza.asc

**Comment by ideasman42** [comment]
Hi, Im keeping `master` matching, `opentoonz` master. Could you rebase onto `linux_fix_wip` branch?
(there are a lot of changes here already in my branch).

**Comment by ideasman42** [comment]
Diff'd with `linux_fix_wip` and theres only one whitespace change.
closing.

**Pull request closed without merging**
